services:
  - type: web
    name: ads-market
    env: ruby
    plan: free
    numInstances: 1
    buildCommand: bin/render-build.sh
    startCommand: bundle exec puma -C config/deploy/puma.rb
    envVars:
      - key: DATABASE_URL
        value: "postgresql://fredbanda_owner:npg_rK3asHZP8bYe@ep-rough-pine-a59dwrn0-pooler.us-east-2.aws.neon.tech/ads_market_db?sslmode=require"
      - key: RAILS_MASTER_KEY
        sync: false